#!/usr/bin/env python3
import os, sys
from PIL import Image

directory = sys[1]

for infile in os.listdir(directory):
  f, e = infile.splitext()
  #f is filename, e is file extension.
  if infile.startswith("ic"):
    #the sample infile images are prefixed with "ic".
    with Image.open(infile) as im:
      filename = os.path.join("/opt/icons/", f)
      #the newly rotated, resized, converted images are to be saved into "/opt/icons/"
      im.rotate(270).resize((128,128)).convert("RGB").save(filename, "JPEG")
